const prouduct = [
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
];

export default prouduct;
