const prouduct = [
	{
		id: 1,
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		id: 2,
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		id: 3,
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		id: 4,
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		id: 5,
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
	{
		id: 6,
		name: "Prouduct 1",
		img: "image1.png",
		price: 1000,
		description: "This is a product description",
		category: "",
		reviews: [],
	},
];

export default prouduct;
